import type { CommunityPost, MarketplaceItem } from './types'

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: 'listing-1',
    title: 'Vintage Leica Camera',
    category: 'Photography',
    condition: 'Excellent',
    price: 1890,
    seller: 'Mina R.',
    location: 'Chicago, IL',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80',
    description: 'A beautifully maintained film camera with original leather case and strap.',
    dateAdded: '2026-07-20',
  },
  {
    id: 'listing-2',
    title: 'Mid-Century Lamp',
    category: 'Decor',
    condition: 'Very Good',
    price: 640,
    seller: 'Jules P.',
    location: 'Austin, TX',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=900&q=80',
    description: 'A sculptural walnut lamp that brings a warm retro glow to any room.',
    dateAdded: '2026-07-18',
  },
  {
    id: 'listing-3',
    title: 'Baseball Card Binder',
    category: 'Sports',
    condition: 'Good',
    price: 120,
    seller: 'Niko T.',
    location: 'Denver, CO',
    image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=900&q=80',
    description: 'A premium binder for organizing a growing card collection with room for sleeves.',
    dateAdded: '2026-07-22',
  },
  {
    id: 'listing-4',
    title: 'Bronze Figurine',
    category: 'Sculpture',
    condition: 'Fair',
    price: 310,
    seller: 'Eli M.',
    location: 'Seattle, WA',
    image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
    description: 'Small but striking bronze piece with light patina and a timeless profile.',
    dateAdded: '2026-07-24',
  },
]

export const communityPosts: CommunityPost[] = [
  {
    id: 'post-1',
    user: 'Sonia',
    avatar: 'https://i.pravatar.cc/100?img=32',
    title: 'Retro Radio Find',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1518444065439-e933c06ce9cd?auto=format&fit=crop&w=900&q=80',
    caption: 'Found this art deco radio at a weekend flea market and it still works perfectly.',
    likes: 128,
    comments: 19,
    saved: false,
  },
  {
    id: 'post-2',
    user: 'Drew',
    avatar: 'https://i.pravatar.cc/100?img=15',
    title: 'Modern Vinyl Drop',
    category: 'Music',
    image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=900&q=80',
    caption: 'A tiny stack of records from the 70s that made my week.',
    likes: 90,
    comments: 12,
    saved: true,
  },
  {
    id: 'post-3',
    user: 'Ava',
    avatar: 'https://i.pravatar.cc/100?img=47',
    title: 'Collector Spotlight',
    category: 'General',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80',
    caption: 'Sharing the newest picks from my cabinet display, including a hand-painted ceramic set.',
    likes: 73,
    comments: 8,
    saved: false,
  },
]
